domain: jinny.to
url: https://jinny.to
baseurl:

title: Jinny To
email: "hello@jinny.to"
author: Jinny To

lang: en

plugins:
  - jekyll-seo-tag

color: "#00CEFD"

rrss:
  email: "hello@jinny.to"
  linkedin: "https://www.linkedin.com/in/jinnyto"